apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
  labels:
    app.kubernetes.io/name: counter
spec:
  replicas: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: counter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: counter
    spec:
      containers:
      - name: counter
        image: host.docker.internal:5001/counter:latest
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - name: http
          containerPort: 8080
