apiVersion: v1
kind: Service
metadata:
  name: counter-service
spec:
  selector:
    app.kubernetes.io/name: counter
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
